# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ca0a6c101cc8f836fe71758c036aa3ee9c98e36d7f919412ee8897dcd42aa1a7d3e2388c9d0062f68d9e33c10310c86fa0fe62fcae1c45afd18ab0878179ba

test:
  secret_key_base: a265f727460f7e60778ff84ca07c2b5afd42ee2151e13ff3e8c993562064fa977935d48f4e7e983e0e1c80be5c66c89c3e94a4a9a085c2f7b26a98f537869304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c07f043b240d4e6e585b8c433a6fbaf92cf911db8acd8cc54c3a4c115c4a4ed341cc4bab4c89fcb06c3d6b97f1080815ece45b51738bfcb7c2d96f95f57baffa 
